### ISSUE TITLE
Question -- How do you update the data and refresh the table?

### ISSUE THREAD

**Issue by kglasnapp** [ragardner/tksheet#12]
I have the following code:

def vChanged(self):
        print("---  Something Changed ---")
        self.inData = [("Keith",), ("Sue",)]
        f = False
        if f:
            self.sheet.data_reference(self.inData)
            self.sheet.set_sheet_data([self.inData])
            self.sheet.refresh()
        else:
            self.sheet = ts.Sheet(self.fileTab, data=self.inData, headers=[
                "File Name"], set_all_heights_and_widths=True, width=300, height=700)
            self.sheet.grid(row=2, column=0, columnspan=6)

If the variable f is False - The table updates with the new data but probably that is not the correct way to refresh. If the variable f is True the table does not update correctly - Note: I initially create the table using the the last two lines in the code above.

Great tool -- Keep up the good work
Thanks for your support

**Comment by kglasnapp** [comment]
I was using tabs. After getting rids of tabs I got the table to update but for some reason the data was displayed as columns instead of rows???  I played around with a number of options with self.sheet.set_sheet_data(inData) and self.sheet.data_reference(inData) but no luck. The table would never update correctly. The method with f set to false seems to work.

**Comment by ragardner** [comment]
Hi there, sorry for the lateness of my response,

With `f` set to `True` in your example there are three reasons why it's not working

the first is that the function `set_sheet_data()` requires a list of lists, not a list of tuples

the second is you do not need to use both `set_sheet_data()` and `data_reference()` just one of them will do

the third is that you have wrapped `self.inData` in square brackets which I think might be why is comes out as columns, just `self.sheet.set_sheet_data(self.inData)` should do if your data is already a list of lists

Also I should mention that with `f` set to `False` you seem to be creating a 2nd table? I'm not sure because I can't see the rest of your code but you shouldn't need to do that, except in perhaps circumstances where you want to maintain every aspect of multiple tables and switch between them or something

Also you're correct in thinking that `.refresh()` is the refresh function for the table

Let me know if this hasn't solved your problem or you have more questions
