### ISSUE TITLE
Binding for cell edit begin

### ISSUE THREAD

**Issue by cpellet** [ragardner/tksheet#13]
Hello,

I was wondering if it would be possible to implement a binding similar to edit_cell, except for when the user starts to edit a cell?

Thank you in advance

**Comment by ragardner** [comment]
@cpellet Hi, sorry for the lateness of my response,

I have implemented this binding, it activates immediately upon a user opening the cell edit window, the variable it sends to your binded function is a tuple of `(<row index>, <column index>, <key pressed>)

You can use the binding like so:

`self.sheet_demo.extra_bindings([("begin_edit_cell", <put your function name here>)])`

You can deactivate the binding like so:

`self.sheet_demo.extra_bindings([("begin_edit_cell", None)])`

Thank you for your feedback and if you have any more questions let me know

**Comment by cpellet** [comment]
Perfect! Thanks a lot for your work!

**Comment by cpellet** [comment]
Hello again,

I have spotted a small bug with this new binding: if the cell's content is updated and the table is refreshed right at the start of the editing, the changes aren't taken into account. For instance:
`    def edit_cell_begin(self, response):
        self.sheet.set_cell_data(response[0], response[1], "edit mode")
        self.sheet.refresh(False, False)`
doesn't update the text box to "edit mode".

Would there be an easy fix for this?

Thank you in advance for your time

**Comment by ragardner** [comment]
@cpellet 

Yes I absolutely put it in the wrong spot, not thinking about the consequences of getting the value before it, if convenient could you check if it is totally fixed for you in `4.5.8`? I actually changed it again slightly after your pull request because I wondered about the impact of the cell being empty and so it putting in the `event.char` value anyway

Here are the release notes:
### Version 4.5.8
 - Add function `set_text_editor_value()`
 - Moved internal `begin_cell_edit` code slightly
 - Make Alt-Return on text editor only increase text window height if too small

**Comment by cpellet** [comment]
@ragardner 
Yes, this is perfect, works as expected. It might be worth explaining the difference between `set_text_editor_value()` and `set_cell_data()` in the documentation now, as this is quite ambiguous.
