### ISSUE TITLE
Typing in cell not yet in edit mode loses character

### ISSUE THREAD

**Issue by cpellet** [ragardner/tksheet#19]
If an empty cell is selected, the first keystroke goes into switching the cell in edit mode. Would be good if the character could be already entered in the cell after the first keystroke.

**Comment by ragardner** [comment]
Currently if there's an extra begin edit cell function it will use the text from the sheet data no matter the keystroke but I think there are far too many extra cell edit bindings and it's messy and needs cleaning up,

I'll work on it now, thanks for letting me know

**Comment by ragardner** [comment]
@cpellet I think it should be fixed now;

To put something other than the keypress into the cell edit window you will need to use

```python
self.sheet.extra_bindings("begin_edit_cell", <your begin edit cell function name here>)
```
or as a list of tuples if you have more than one binding to do

If your begin edit cell function returns anything other than `None` then that return value will be the one that appears inside the cell edit window, currently it has to be a string, but I'll change that to any type with a str() method in the future

Full release notes:

### Version 4.7.3
 - Make `"begin_edit_cell"` and `"end_edit_cell"` the only two edit cell bindings for use with `extra_bindings()` function (although `"edit_cell"` still works and is the equivalent of `"end_edit_cell"`)
 - Make it so if `"begin_edit_cell"` binding returns anything other than `None` the text in the cell edit window will be that return value otherwise it will be the relevant keypress
 - Prevent auto resize from firing two redraw commands in one go
 - Fixed issue where clicking outside of cell edit window and Sheet would return focus to the Sheet widget anyway
 - Fixed issues where row/column select highlight would be lower in canvas than cell selections
 - Hopefully simplified cell edit code a bit
 - Fix undo delete columns error for python versions < 3.8

**Comment by ragardner** [comment]
I think it still needs more work though to integrate auto fill properly and fix some ongoing issues like Escape focus and cell selection/highlight rectangles raise/lower order

**Comment by cpellet** [comment]
Thank you for the quick fix! Now works as intended
![tksheet0](https://user-images.githubusercontent.com/18552249/82749907-bed83e80-9dac-11ea-8849-d2e2c4619478.gif)
