### ISSUE TITLE
Keypad enter button ignored

### ISSUE THREAD

**Issue by Myoldmopar** [ragardner/tksheet#220]
Hello, first, I am super happy to be using tksheet.  I'm working on bumping up to 7.0, looks like some great updates.

I'm not sure if this is "as-designed", or if it was always like this or if it is new behavior, but when I am entering data into a tksheet, the enter key over on my numeric keypad is not recognized as a submit button.  I tried running the basic usage example [here](https://github.com/ragardner/tksheet/wiki/Version-7#usage-examples), with 7.0.0, and if I go through and try to enter numeric data into the cells, and use the enter key over there, it won't complete the edit.  I have to move over and use the normal enter key.

Apologies if this is known or intentional, I've been scanning docs and haven't noticed anything about it.  And entering numeric data into the sheet seems like a typical behavior where you'd want that enter key operating.

Thank you!

**Comment by ragardner** [comment]
Hi there,

Thanks for your report, this was neither known nor intentional so I really appreciate you letting me know!

I unfortunately do not have a keyboard with a numpad to test this at the moment but it's possibly fixed in `7.1.8` where I added the bindings `"<KP_Enter>"` for closing the cell text editor and also `"<Alt-KP_Enter>"` for creating a new line in the cell text editor.

I have no real idea if these bindings will work sorry, I am following guidance on this question:
[https://stackoverflow.com/questions/74889898/numeric-enter-key-not-binding-in-python-tkinter-application-in-raspberrypi-os](https://stackoverflow.com/questions/74889898/numeric-enter-key-not-binding-in-python-tkinter-application-in-raspberrypi-os)

If you want to, let me know if they don't work and I'll try something else

Here is the changelog for `7.1.8`:

### Version 7.1.8
#### Fixed:
- Issue with setting sheet xview/yview immediately after initialization
- Visual selection box issue with boxes with 0 length or width

#### Addressed:
- Issue [220](https://github.com/ragardner/tksheet/issues/220)

#### Added:
- Functions:
    - `boxes` setter for use with `Sheet.get_all_selection_boxes_with_types()` or `Sheet.boxes` property
    - `selected` setter
    - `all_rows` property to get `all_rows_displayed` `bool`
    - `all_columns` property to get `all_columns_displayed` `bool`
    - `all_rows` setter to set `all_rows_displayed` `bool`
    - `all_columns` setter to set `all_columns_displayed` `bool`
    - `displayed_rows` setter uses function `Sheet.display_rows()`
    - `displayed_columns` setter uses function `Sheet.display_columns()`

#### Removed:
- All parameters from function `Sheet.after_redraw()`
- Warnings about version changes from `Sheet()` initialization
- `within_range` parameters from internal `get_selected_cells`/`get_selected_rows`/`get_selected_columns` functions

**Comment by Myoldmopar** [comment]
Can confirm!  With 7.1.8, the key pad enter key is working happily, so I can rapidly enter numeric data into cells.  Thanks!  I'll close this issue.
