### ISSUE TITLE
Quotes multiplies when i copy text from cell with ctrl+c or popup menu.

### ISSUE THREAD

**Issue by serghPeppa** [ragardner/tksheet#221]
It happens only if this text already has quotes, for example: 
word word word "word"
And if i copy this and paste, no matter where, it turns in to:
"word word word ""word"""
Can you please help me to deal with that?

**Comment by ragardner** [comment]
Hello,

Thank you very much for bringing this issue to my attention and I'm sorry it was an issue to begin with

For single cell copy/cut operations this should be fixed in version `7.1.11`

I have not changed this behaviour when dealing with multiple cells however as I let the python csv library handle that

Let me know if you have further issues,

Cheers!

**Comment by serghPeppa** [comment]
I updated and all working correctly! Great! Thank you very much for for the quick response! Tksheet is the best table for tkinter!
