### ISSUE TITLE
Is there a way to set copy and paste bindings on cyrillic layout?

### ISSUE THREAD

**Issue by serghPeppa** [ragardner/tksheet#223]
In Cyrillic layout copy and paste works on same keys but 'v' is 'м'(em), and 'c' is 'с'(es). And when i change layout to Russian or Ukrainian copy and paste stops working in sheet.
![keyboard image](https://github.com/ragardner/tksheet/assets/120131038/564fbbec-0bc5-4611-a305-5f9c268d10ca)

**Comment by ragardner** [comment]
Hello,

Thanks for your question and the interesting code snippet,

I am not sure how best to get those custom events working in tksheet at the moment, it will take some experimentation if I do decide to implement it

In the meantime, would this solution work for you? You can replace the characters with whichever you need

```python
sheet.set_options(paste_bindings=["<Control-м>", "<Control-М>"])
```

More info here: [https://github.com/ragardner/tksheet/wiki/Version-7#changing-key-bindings](https://github.com/ragardner/tksheet/wiki/Version-7#changing-key-bindings)

**Comment by serghPeppa** [comment]
It's not working if i type cyrillic symbol inside it. It gives this error:
_tkinter.TclError: bad event type or keysym "с"
Maybe you can make an overload of this option, where I will be able to use keycode instead of keysym?
This will immediately solve my problem.

**Comment by ragardner** [comment]
Hello,

I am working on this and I think I have a solution that will make the code you provided work for tksheet, meaning that `widget.event_generate("<<Copy>>")` will tell tksheet to run the copy function.

I am not currently working on ways of binding the keycodes though sorry, this seems a bit more complex and would warrant more investigation.

There will also separately be an optional way of specifically binding the `"<<Copy>>"` event to tksheet.

Your help has been invaluable in figuring this out thank you, I will let you know when there is a new release

**Comment by serghPeppa** [comment]
I'm very glad to hear this! I hope you can do this. Thank you for your work!

**Comment by ragardner** [comment]
Hello,

I have released a new version which should allow you to call `event_generate()` on a Sheet, with `"<<Copy>>"` and so also for paste, delete, cut, undo, redo and selectall

Some new documentation here: https://github.com/ragardner/tksheet/wiki/Version-7#tkinter-and-tksheet-events

### Version 7.1.22
#### Addressed:
- Issue [222](https://github.com/ragardner/tksheet/issues/222)
- Issue [223](https://github.com/ragardner/tksheet/issues/223)

#### Fixed:
- Massive lag when pasting large amounts of data, caused by using Python `csv.Sniffer().sniff()` without setting sample size, now only samples 5000 characters max

#### Changed:
- Added `widget` key to emitted event `dict`s which can be either the header, index or table canvas. If you're using `pickle` on tksheet event `dict`s then you may need to delete the `widget` key beforehand
- Added `Highlight`, `add_highlight`, `new_tk_event` and `get_csv_str_dialect` to tksheet namespace
- Some old functions which used to return `None` now return `self` (`Sheet`)
- Re-add old highlighting functions to docs
- Event data from moving rows/columns while rows/columns are hidden no longer returns all displayed row/column indexes in the `dict` keys `["moved"]["rows"]["data"]`/`["moved"]["columns"]["data"]` but instead returns only the rows/columns which were originally moved.
- Add `Shift-Return` to text editor newline bindings
- Internal `close_text_editor()` function parameters
- Function `close_text_editor()` now closes all text editors that are open

#### Added:
- New parameters to `dropdown()`:
    - `edit_data` to disable editing of data when creating the dropdowns
    - `set_values` so a `dict` of cell/column/row coordinates and values can be provided instead of using `set_value` for every cell in the span
- New emitted events - issue [223](https://github.com/ragardner/tksheet/issues/223):
    - `"<<Copy>>"`
    - `"<<Cut>>"`
    - `"<<Paste>>"`
    - `"<<Delete>>"`
    - `"<<Undo>>"`
    - `"<<Redo>>"`
    - `"<<SelectAll>>"`

#### Improved:
- Dropdown box scrollbars will only display when necessary
- Some themes colors
- Old function `highlight_cells()` slight performance boost when calling it thousands of times
- Added parameters back to the functions `dropdown()`/`checkbox()` for help when writing code

**Comment by serghPeppa** [comment]
You are a genius! You solve it so quick and elegant! Thank you!
But there was a little issue, if you want your sheet to be `readonly` you need to set filter on `Canvas` in your `<<Paste>>` event:
```
def _onKeyRelease(event):
    ctrl  = (event.state & 0x4) != 0
    if event.keycode==86 and  ctrl and event.keysym.lower() != "v": 
        if event.widget.winfo_class() not in ("Canvas"):
            event.widget.event_generate("<<Paste>>")

    if event.keycode==67 and  ctrl and event.keysym.lower() != "c":
        event.widget.event_generate("<<Copy>>")

main.bind_all("<Key>", _onKeyRelease, "+")
```
But for me it's 100% resolved. And again, thank you so much!
