### ISSUE TITLE
Column header data not made when creating new columns

### ISSUE THREAD

**Issue by MagnificentCreature** [ragardner/tksheet#225]
I open an empty sheet with (empty) data [[]], 

I do right click create new column, then I try to save.

However 

print(self.sheet.get_header_data())

Does not do anything and I am unable to save the header data

Edit: also seems to throw a silent error, code bellow the print function doesnt run
Edit 2: The error indicates I need to pass in a c (probably column) but even if I do so, nothing gets printed

**Comment by ragardner** [comment]
Hello,

Thanks very much for bringing this to my attention,

There's a few things going on here,

After examining the code which deals with inserting columns and rows I found that it was indeed an issue that it wasn't inserting header/row index cells upon inserting columns/rows

After making the necessary modifications and testing them a bit I found other issues that needed fixing involving similar functionality

> Edit 2: The error indicates I need to pass in a c (probably column) but even if I do so, nothing gets printed

If you saw an empty line when printing that is probably intended. if either the header (`sheet.MT._headers`) wasn't long enough to cover the index you're printing or if it's an empty cell then in this case it would only print an empty string

To test this out you can do `print(self.sheet.get_header_data(0, get_displayed=True))` which should print whatever the header is displaying instead of the underlying cell data

Of course there is the possibility that a silent error was being produced and blocking the printing, and you saw no new empty line, this may or may not be fixed now in `7.1.24`

Anyway thanks again and here are the release notes:

### Version 7.1.24
#### Fixed:
- Error on paste into empty sheet with `expand_sheet_if_paste_too_big`
- Data shape not being correct upon inserting a single column or row into an empty sheet
- Potential for `insert_columns()` to cause issues if provided columns are longer than current number of sheet rows
- [225](https://github.com/ragardner/tksheet/issues/225) Insert columns and insert rows not inserting blank cells into header/row index, issue seen with either:
    - Right clicking and using the in-built insert functionality
    - Using the `Sheet()` functions with an `int` for first parameter
- Wrong sheet dimensions caused by a paste which expands the sheet
- Wrong new selection box dimensions after paste which expands the sheet
- `set_options()` with `table_font=` not working

#### Changed:
- `expand_sheet_if_paste_too_big` replaced by `paste_can_expand_x` and `paste_can_expand_y`. To avoid compatibility issues using `expand_sheet_if_paste_too_big` will set both new options

#### Improved:
- Additional protection against issue [224](https://github.com/ragardner/tksheet/issues/224) but with `auto_resize_row_index="empty"` which is the default setting

**Comment by MagnificentCreature** [comment]
Works now, thanks!
