### ISSUE TITLE
[BUG] if you hide a column next to a column that has a combobox, the combobox will not move to a new location next to the column

### ISSUE THREAD

**Issue by lmcdd** [ragardner/tksheet#36]
![Снимок экрана_2020-08-11_18-04-18](https://user-images.githubusercontent.com/6673326/89914408-a7fff600-dbfd-11ea-8d62-95e7e7e06c77.png)

**Comment by ragardner** [comment]
Hi, thank you for the report

This is basically because the code has not been written to move drop downs around with sheet actions such as inserting/deleting columns or hiding columns,

There is a slight conundrum with fixing this, at the moment creating a drop down box is done by using the displayed column indexes and doesn't include hidden columns;

Would it be okay if the fix included making the chosen column index to create a drop down the data column? e.g. If you had displayed columns == [0, 1, 2, 4] and you created a drop down in column 3 it would not show in the sheet, it may mean changing your existing code

Lastly I'm afraid due to having an important commitment lasting a couple of weeks I might not be able to find the time to fix this for a little while, we'll see...

**Comment by ragardner** [comment]
This should be fixed in `4.9.7` but all the dropdown functions now use the data indexes as opposed to displayed column indexes, e.g. when getting data from a dropdown while hiding columns the column index will be the data index

But try it out and let me know if it's not working correctly

**Comment by lmcdd** [comment]
@ragardner, works great, thank you!
