### ISSUE TITLE
editing

### ISSUE THREAD

**Issue by cyrillxjuday** [ragardner/tksheet#5]
after editing a cell,
when user clicked on a different cell, the wrong cell gets activated.
(the cell that is under the clicked cell).

**Comment by cyrillxjuday** [comment]
<img width="608" alt="ana" src="https://user-images.githubusercontent.com/43101034/70878616-2f5c8180-1ffd-11ea-85d2-ba2ca35ce74c.png">

**Comment by cyrillxjuday** [comment]
btw thanks for this widget sir. I prefer this over tkintertable : )

**Comment by ragardner** [comment]
Hi, thanks for pointing this out in a very easy to understand way and for the complement

I have just fixed it (I think) with version 4.1.6 but I removed the code that moves the cell up to the top of a selected range when the edited cell was at the bottom of the selected range because it wasn't really working very well anyway, I'll possibly put it back in at a later date
