### ISSUE TITLE
Combobox autocomplete instead of Dropdown Boxes

### ISSUE THREAD

**Issue by jayaranah** [ragardner/tksheet#71]
It is possible to use Combobox autocomplete instead of Dropdown Boxes? i want function in a column like Combobox autocomplete that i found here [https://code.activestate.com/recipes/580770-combobox-autocomplete/](url)

**Comment by ragardner** [comment]
This is not something I can look into in any great detail sorry but it seems like you would have to modify tksheets code in _tksheet_main_table.py under function `def create_dropdown(`

Probably modify this code and replace it with the autocomplete widget
```python
widget = TableDropdown(self,
                                 font = self.my_font,
                                 state = state,
                                 values = values,
                                 set_value = set_value,
                                 width = w,
                                 height = h)
```

then modify this code (line 4722 in version 5.0.25)
```python
self.cell_options[(r, c)]['dropdown'][0].dropdown.bind("<<ComboboxSelected>>",
                                                               lambda event: self.get_dropdown_value(canvas_window = window,
                                                                                                     current = current,
                                                                                                     destroy = destroy_on_select,
                                                                                                     set_cell_on_select = set_cell_on_select,
                                                                                                     redraw = redraw,
                                                                                                     recreate = recreate))
```
this 2nd bit of code you will have to make it so that when the user selects an item from the autocomplete box it triggers the tksheet function `get_dropdown_value()` with the same arguments as above

this is so that the underlying sheet data is modified when the user selects an item

**Comment by AJAY-P-37** [comment]
Hi @jayaranah 
I'm also working in a similar autocomplete dropdown in tksheets.
Did you able to do that? If so can you help me with the code?
