### ISSUE TITLE
Autofit to cell contents

### ISSUE THREAD

**Issue by PieNiusek** [ragardner/tksheet#9]
Hello, 

Is there property that make auto fit cells to content eg. multi line values?
I know it is possible to make autoresize by double click on each cell to fit to content. Is it possible to make same on startup to every cell?

**Comment by ragardner** [comment]
There is currently not a function that does every cell, there are ones that do the section of the table that is displayed, `column_width("displayed", "text")` and `row_height("displayed", "text")` use argument `redraw` with `True` or `False` to set whether or not to redraw immediately after resize

This is because of performance, it's can be quite slow to split the contents of every cell and measure the text width and height (to measure it has to draw the text on a separate canvas and use bbox and then delete it - it does it for every line) although it does depend on the size of the table

Now that you mention it, I will probably add a function that goes through all the data and resizes everything with the option to use at startup

**Comment by PieNiusek** [comment]
It would be great If you are able to add that function.
Is there is a way to set manually width of each column, and height of each row separatelly? As long there is no function prepared for this I want to try write my own function to set propper width and height.

**Comment by ragardner** [comment]
Yes, for individual rows/columns:

`.column_width(column = <put index here>, width = <put width in pixels here>)`
`.row_height(row = <put index here>, height = <put height in pixels here>)`

or for the entire sheet:

`.set_column_widths(<list of widths in pixels e.g. [120, 120, 120, 120]>)`
`.set_row_heights(<list of heights in pixels e.g. [30, 30, 30, 30]>)`

**Comment by ragardner** [comment]
I am testing a function now that takes 4 seconds to do 60,000 cells (2000 rows by 30 columns) on an AMD Ryzen 3600 CPU, it does fit all cells in the sheet both heights and widths

Let me know what you think about this

**Comment by PieNiusek** [comment]
In my use case it is totally acceptable time.

**Comment by ragardner** [comment]
I will hopefully have it finished in like 48 hours

**Comment by ragardner** [comment]
@PieNiusek Ok, I have updated the library on pypi, here's the release notes:

### Version 4.3.6
 - Add function `get_currently_selected()`
 - Add functions `self.sheet_demo.set_all_column_widths()`, `self.sheet_demo.set_all_row_heights()`, `self.sheet_demo.set_all_cell_sizes_to_text()`
 - Add argument `set_all_heights_and_widths` to startup, use `True` or `False`
 - Improve performance of all resizing functions
 - Make resizing detect text dimensions for full row/column, not just what is displayed

**Comment by ragardner** [comment]
@PieNiusek Sorry there's a couple of bugs with the resizing stuff, will notify here when fixed

**Comment by ragardner** [comment]
It seems to be working with 4.3.7, let me know if you encounter any issues or close the issue if it's working

**Comment by PieNiusek** [comment]
@ragardner I was a little bit off so I couldn't answer. Thank you for yor engagement in making this function. You make it really fast. It works great, thanks for implement this.
